# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arssha/projects/school/bank

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arssha/projects/school/bank

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arssha/projects/school/bank/CMakeFiles /Users/arssha/projects/school/bank//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arssha/projects/school/bank/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bank

# Build rule for target.
bank: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bank
.PHONY : bank

# fast build rule for target.
bank/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/build
.PHONY : bank/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

BankAccounts/BankAccount.o: BankAccounts/BankAccount.cpp.o
.PHONY : BankAccounts/BankAccount.o

# target to build an object file
BankAccounts/BankAccount.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/BankAccount.cpp.o
.PHONY : BankAccounts/BankAccount.cpp.o

BankAccounts/BankAccount.i: BankAccounts/BankAccount.cpp.i
.PHONY : BankAccounts/BankAccount.i

# target to preprocess a source file
BankAccounts/BankAccount.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/BankAccount.cpp.i
.PHONY : BankAccounts/BankAccount.cpp.i

BankAccounts/BankAccount.s: BankAccounts/BankAccount.cpp.s
.PHONY : BankAccounts/BankAccount.s

# target to generate assembly for a file
BankAccounts/BankAccount.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/BankAccount.cpp.s
.PHONY : BankAccounts/BankAccount.cpp.s

BankAccounts/Checking/Checking.o: BankAccounts/Checking/Checking.cpp.o
.PHONY : BankAccounts/Checking/Checking.o

# target to build an object file
BankAccounts/Checking/Checking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Checking/Checking.cpp.o
.PHONY : BankAccounts/Checking/Checking.cpp.o

BankAccounts/Checking/Checking.i: BankAccounts/Checking/Checking.cpp.i
.PHONY : BankAccounts/Checking/Checking.i

# target to preprocess a source file
BankAccounts/Checking/Checking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Checking/Checking.cpp.i
.PHONY : BankAccounts/Checking/Checking.cpp.i

BankAccounts/Checking/Checking.s: BankAccounts/Checking/Checking.cpp.s
.PHONY : BankAccounts/Checking/Checking.s

# target to generate assembly for a file
BankAccounts/Checking/Checking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Checking/Checking.cpp.s
.PHONY : BankAccounts/Checking/Checking.cpp.s

BankAccounts/Savings/Savings.o: BankAccounts/Savings/Savings.cpp.o
.PHONY : BankAccounts/Savings/Savings.o

# target to build an object file
BankAccounts/Savings/Savings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Savings/Savings.cpp.o
.PHONY : BankAccounts/Savings/Savings.cpp.o

BankAccounts/Savings/Savings.i: BankAccounts/Savings/Savings.cpp.i
.PHONY : BankAccounts/Savings/Savings.i

# target to preprocess a source file
BankAccounts/Savings/Savings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Savings/Savings.cpp.i
.PHONY : BankAccounts/Savings/Savings.cpp.i

BankAccounts/Savings/Savings.s: BankAccounts/Savings/Savings.cpp.s
.PHONY : BankAccounts/Savings/Savings.s

# target to generate assembly for a file
BankAccounts/Savings/Savings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/BankAccounts/Savings/Savings.cpp.s
.PHONY : BankAccounts/Savings/Savings.cpp.s

Person/Person.o: Person/Person.cpp.o
.PHONY : Person/Person.o

# target to build an object file
Person/Person.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/Person/Person.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Person/Person.cpp.o
.PHONY : Person/Person.cpp.o

Person/Person.i: Person/Person.cpp.i
.PHONY : Person/Person.i

# target to preprocess a source file
Person/Person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/Person/Person.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Person/Person.cpp.i
.PHONY : Person/Person.cpp.i

Person/Person.s: Person/Person.cpp.s
.PHONY : Person/Person.s

# target to generate assembly for a file
Person/Person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/Person/Person.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Person/Person.cpp.s
.PHONY : Person/Person.cpp.s

bank.o: bank.cpp.o
.PHONY : bank.o

# target to build an object file
bank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/bank.cpp.o
.PHONY : bank.cpp.o

bank.i: bank.cpp.i
.PHONY : bank.i

# target to preprocess a source file
bank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/bank.cpp.i
.PHONY : bank.cpp.i

bank.s: bank.cpp.s
.PHONY : bank.s

# target to generate assembly for a file
bank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/bank.cpp.s
.PHONY : bank.cpp.s

cli/cli.o: cli/cli.cpp.o
.PHONY : cli/cli.o

# target to build an object file
cli/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/cli.cpp.o
.PHONY : cli/cli.cpp.o

cli/cli.i: cli/cli.cpp.i
.PHONY : cli/cli.i

# target to preprocess a source file
cli/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/cli.cpp.i
.PHONY : cli/cli.cpp.i

cli/cli.s: cli/cli.cpp.s
.PHONY : cli/cli.s

# target to generate assembly for a file
cli/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/cli.cpp.s
.PHONY : cli/cli.cpp.s

cli/ie/Export.o: cli/ie/Export.cpp.o
.PHONY : cli/ie/Export.o

# target to build an object file
cli/ie/Export.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/ie/Export.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/cli/ie/Export.cpp.o
.PHONY : cli/ie/Export.cpp.o

cli/ie/Export.i: cli/ie/Export.cpp.i
.PHONY : cli/ie/Export.i

# target to preprocess a source file
cli/ie/Export.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/ie/Export.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/cli/ie/Export.cpp.i
.PHONY : cli/ie/Export.cpp.i

cli/ie/Export.s: cli/ie/Export.cpp.s
.PHONY : cli/ie/Export.s

# target to generate assembly for a file
cli/ie/Export.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bank.dir/build.make CMakeFiles/bank.dir/cli/ie/Export.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/cli/ie/Export.cpp.s
.PHONY : cli/ie/Export.cpp.s

tests/Tests.o: tests/Tests.cpp.o
.PHONY : tests/Tests.o

# target to build an object file
tests/Tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/Tests.cpp.o
.PHONY : tests/Tests.cpp.o

tests/Tests.i: tests/Tests.cpp.i
.PHONY : tests/Tests.i

# target to preprocess a source file
tests/Tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/Tests.cpp.i
.PHONY : tests/Tests.cpp.i

tests/Tests.s: tests/Tests.cpp.s
.PHONY : tests/Tests.s

# target to generate assembly for a file
tests/Tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/Tests.cpp.s
.PHONY : tests/Tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bank"
	@echo "... tests"
	@echo "... BankAccounts/BankAccount.o"
	@echo "... BankAccounts/BankAccount.i"
	@echo "... BankAccounts/BankAccount.s"
	@echo "... BankAccounts/Checking/Checking.o"
	@echo "... BankAccounts/Checking/Checking.i"
	@echo "... BankAccounts/Checking/Checking.s"
	@echo "... BankAccounts/Savings/Savings.o"
	@echo "... BankAccounts/Savings/Savings.i"
	@echo "... BankAccounts/Savings/Savings.s"
	@echo "... Person/Person.o"
	@echo "... Person/Person.i"
	@echo "... Person/Person.s"
	@echo "... bank.o"
	@echo "... bank.i"
	@echo "... bank.s"
	@echo "... cli/cli.o"
	@echo "... cli/cli.i"
	@echo "... cli/cli.s"
	@echo "... cli/ie/Export.o"
	@echo "... cli/ie/Export.i"
	@echo "... cli/ie/Export.s"
	@echo "... tests/Tests.o"
	@echo "... tests/Tests.i"
	@echo "... tests/Tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

